# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddf233e6e37584ff611e9589361ecf5f1c4cce63ea2d48347016b98e76829283be23f1315e00c06ad4863174e9ae6dab5542473bfa12a95e0b0704f0a34a1d04

test:
  secret_key_base: 3f7d5f67e22f8bc50e4b7e63b1606a541fd40d165f94c355f81e05c998498b7a9b59bedc9ab0a3af2991eb3951b08a276211c4a59744fe4e053a8cebe101da68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
