language: ruby
rvm:
  - 2.0.0
  - 2.1.0
script:
  - RAILS_ENV=test bundle exec rake --trace db:create db:migrate db:test:prepare spec cucumber
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq aspell aspell-en libaspell-dev
before_script:
  - cp config/database.yml.travis config/database.yml
bundler_args: -j4 --without development production --quiet
services:
  - redis-server